### ISSUE TITLE
Outdated Message Sequence Chart Rendered On Save

### ISSUE THREAD

**Issue by we-eff** [mscgenjs/mscgenjs.github.io#1]
The _save_ dialog shows __unexpected behaviour__ in following circumstances:
- When the _save_ dialog is opened, the user can choose in which file format the chart should be saved.
- This dialog remains opened (which it does by default).
- The textual description is changed, the preview is updated.
- A file format is chosen again in the still open _save_ dialog.
- __Not the chart which is shown in preview, but the chart which was described before opening the _save_ dialog is rendered.__

**Comment by sverweij** [comment]
hi @we-eff thanks for raising this issue. This repository is not active at the moment. 

Did you want to raise an issue on https://github.com/sverweij/mscgen_js (which has the code for mscgen.js.org)? 

If so, I can see the behaviour you see is unexpected. Probably the save dialog should be closed when you have another interaction with the app. I've put an [item on mscgen_js' backlog](https://github.com/sverweij/mscgen_js/projects/1#card-45903814) so it can be picked up some time in the future.
